AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for selenium

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 1024

Resources:
  SeleniumBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 600
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        SeleniumBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /selenium_bot
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./selenium_bot
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SeleniumBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Selenium Bot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/selenium_bot/"
  SeleniumBotFunction:
    Description: "Selenium Bot Lambda Function ARN"
    Value: !GetAtt SeleniumBotFunction.Arn
  SeleniumBotFunctionIamRole:
    Description: "Implicit IAM Role created for Selenium Bot function"
    Value: !GetAtt SeleniumBotFunctionRole.Arn
