AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-selenium

  Sample SAM Template for lambda-selenium

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  # DeploymentPermission:
  #   Type: "AWS::Lambda::LayerVersionPermission"
  #   Properties:
  #     Action: lambda:GetLayerVersion
  #     LayerVersionArn: !Ref ChromiumLayer
  #     Principal: '*'

  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium-selenium-layer
      Description: Headless Chromium and Selenium WebDriver
      ContentUri: ./layers/selenium-binaries
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  LambdaSelenium:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 764
      Timeout: 300
      # PackageType: Image
      # Architectures:
      #   - x86_64
      # Events:
      #   SeleniumBot:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /selenium_bot
      #       Method: get
      Layers:
        - !Ref ChromiumLayer
      Environment:
        Variables:
          CLEAR_TMP: "true"
          PATH: /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin:/tmp/bin:/tmp/bin/lib
